name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
- deployment
pr:
- deployment

pool:
  vmImage: ubuntu-latest

stages:
  - stage: 'build'
    displayName: 'Initial steps'
    jobs:
      - job: 'build'
        displayName: 'Build App'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '14.x'
            displayName: 'Install Node.js'
          - script: |
              npm install --legacy-peer-deps
              npm run build
            displayName: 'Install deps and build'

  - stage: 'deploy'
    displayName: 'Publish & Deploy App'
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    jobs:
      - job: 'publish'
        displayName: 'Publish Artifact'
        steps:
          - task: CopyFiles@2
            displayName: 'Copy files'
            inputs:
              sourceFolder: 'build' 
              Contents: '**/*'
              TargetFolder: '$(Build.ArtifactStagingDirectory)'
              cleanTargetFolder: true
          - task: ArchiveFiles@2
            displayName: 'Archive files'
            inputs:
              rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
              includeRootFolder: false
              archiveType: zip
              archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
              replaceExistingArchive: true
          - task: PublishBuildArtifacts@1
            displayName: 'Publish Build Artifacts'
            inputs:
              pathtoPublish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip

      - job: 'deploy'
        displayName: 'Deploy App'
        steps:
          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'Azure subscription 1 (0033c6eb-8348-44fc-910f-492d6df58064)'
              appType: 'webAppLinux'
              appName: 'eventexpress-frontend-dev'
              package: '$(System.ArtifactsDirectory)/$(Build.BuildId).zip'
              runtimeStack: 'NODE|14-lts'
              startUpCommand: 'pm2 serve /home/site/wwwroot --no-daemon --spa'